#!/usr/bin/env groovy

node {
    stage('checkout') {
        checkout scm
    }

    stage('check java') {
        sh "java -version"
    }

    stage('clean') {
        sh "cd online-store && chmod +x gradlew"
        sh "cd online-store && ./gradlew clean --no-daemon"
    }
    stage('nohttp') {
        sh "cd online-store && ./gradlew checkstyleNohttp --no-daemon"
    }

    stage('npm install') {
        sh "cd online-store && ./gradlew npm_install -PnodeInstall --no-daemon"
    }

    stage('backend tests') {
        try {
            sh "cd online-store && ./gradlew test integrationTest -PnodeInstall --no-daemon"
        } catch(err) {
            throw err
        } finally {
            junit '**/build/**/TEST-*.xml'
        }
    }

    stage('frontend tests') {
        try {
            sh "cd online-store && ./gradlew npm_run_test -PnodeInstall --no-daemon"
        } catch(err) {
            throw err
        } finally {
            junit '**/build/test-results/TESTS-*.xml'
        }
    }

    stage('packaging') {
        sh "cd online-store && ./gradlew bootJar -x test -Pprod -PnodeInstall --no-daemon"
        archiveArtifacts artifacts: '**/build/libs/*.jar', fingerprint: true
    }

    stage('deployment') {
        sh "cd online-store && ./gradlew deployHeroku --no-daemon"
    }

}
